NETWORK_PASSPHRASE="Pi Network"
HOME_DOMAIN="pi-nexus-autonomous-banking-network.kosasih.github.io"

# Founder
FOUNDERS="KOSASIH"
FOUNDER_WALLET="GCKUNNC6X6LKYJXKTQEJAQQ2J6NTIHMRNJFM2KY6KIBB46BOPMKVXDQN"

[[CURRENCIES]]
code="PiNEXUS"
issuer="GC_ISSUER_WALLET_KAMU_DISINI" # GANTI DENGAN WALLET ISSUER KAMU
name="Pi-Nexus Autonomous Stablecoin"
desc="The most super smart stablecoin for Pi Nexus Autonomous Banking Network. Total Supply: 100B. 20% to Founder: GCKUNNC6X6LKYJXKTQEJAQQ2J6NTIHMRNJFM2KY6KIBB46BOPMKVXDQN"
image="https://pi-nexus-autonomous-banking-network.kosasih.github.io/logo.png"
