# Define constants used throughout the project
SECRET_KEY = 'SECRET_KEY_HERE'
ENCRYPTION_KEY = 'ENCRYPTION_KEY_HERE'
ACCESS_CONTROL_ALLOW_ORIGIN = '*'
RATE_LIMITING_ENABLED = True
RATE_LIMITING_THRESHOLD = 100
